# Generated by Django 3.1.7 on 2021-04-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20210402_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=130, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Published Date'),
        ),
    ]
